# NUMPY

A package in python which stands for ‘Number Python’

It is used for mathematical and scientific computations, which contains multi-dimensional arrays and matrices.

Using linalg module we can perform linear algebra also.


# Numpy Array

An array is a collection of items of same data type stored at contiguous memory locations.

It works faster than list.

An array can be n-dimensional.


In [1]:
import numpy as np

In [2]:
##creating array


In [5]:
score=[80,90,100,87]
print(score)
print(type(score))
score_array=np.array(score)
print(score_array)
print(type(score_array))

[80, 90, 100, 87]
<class 'list'>
[ 80  90 100  87]
<class 'numpy.ndarray'>


In [6]:
import array
n1 = array.array('i', [10,56,87]) 
print(n1)
print(type(n1))

array('i', [10, 56, 87])
<class 'array.array'>


In [14]:
import time
size = 100000  
list1 = range(size)
list2 = range(size)
array1 = np.arange(size) 
array2 = np.arange(size)
 
initialTime = time.time()
list3 = [(a * b) for a, b in zip(list1, list2)]
 
print("Time taken by Lists :",
      (time.time() - initialTime),
      "seconds")
 
initialTime = time.time()
array3 = array1 * array2
 
print("Time taken by NumPy Arrays :",
      (time.time() - initialTime),
      "seconds")

Time taken by Lists : 0.026427268981933594 seconds
Time taken by NumPy Arrays : 0.0 seconds


In [17]:
size = 1000000 
  
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
array1 = np.arange(size)
array2 = np.arange(size)
 
print("\nConcatenation:")
initialTime = time.time()
list3 = list1 + list2
print("Time taken by Lists :",
      (time.time() - initialTime),
      "seconds")
  
# NumPy array
initialTime = time.time()
array3 = np.concatenate((array1, array2),
                          axis = 0)
 
# calculating execution time
print("Time taken by NumPy Arrays :",
      (time.time() - initialTime),
      "seconds")
 
 
# Dot Product
dot = 0
print("\nDot Product:")
 
# list
initialTime = time.time()
for a, b in zip(list1, list2):
        dot = dot + (a * b)
         
# calculating execution time
print("Time taken by Lists :",
      (time.time() - initialTime),
      "seconds")
initialTime = time.time()
array4 = np.dot(array1, array2)
 
# calculating execution time
print("Time taken by NumPy Arrays :",
      (time.time() - initialTime),
      "seconds")


Concatenation:
Time taken by Lists : 0.04713749885559082 seconds
Time taken by NumPy Arrays : 0.0 seconds

Dot Product:
Time taken by Lists : 0.3595116138458252 seconds
Time taken by NumPy Arrays : 0.0 seconds


# Create NumPy array of random numbers


In [7]:
a=np.random.random(size=5)
a

array([0.41493472, 0.61688815, 0.71079087, 0.57805729, 0.08690023])

numpy.random.random() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the
half-open interval [0.0, 1.0).
 The required number of random numbers is passed through the ‘size’ parameter .
 

In [8]:
np.random.rand(5)

array([0.04625224, 0.97884904, 0.99581662, 0.84616433, 0.79633339])

The rand() creates an array of the given shape and populates it with random variables derived
from a uniform distribution between (0, 1)


In [9]:
np.random.randn(5)

array([ 0.45172997, -1.27590635,  0.4377912 , -0.890759  ,  0.13852583])

The randn() returns a values from the "Standard Normal" distribution.

standard Normal Distribution has mean 0 and standard deviation 1.


In [4]:
np.random.randint(7)


3

In [5]:
np.random.randint(1,12,5)

array([4, 7, 9, 8, 1])

It returns an array of specified shape and fills it with random integers from low (inclusive) to 
high (exclusive), i.e. in the interval [low, high).

In [6]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [9]:
np.arange(1,12,2,'float')

array([ 1.,  3.,  5.,  7.,  9., 11.])

The np.arange() creates a NumPy array.

The numbers generated have the same difference.

Numpy.arange (start, stop,step,dtype)



In [10]:
np.linspace(start=0,stop=50,num=15,retstep=True)

(array([ 0.        ,  3.57142857,  7.14285714, 10.71428571, 14.28571429,
        17.85714286, 21.42857143, 25.        , 28.57142857, 32.14285714,
        35.71428571, 39.28571429, 42.85714286, 46.42857143, 50.        ]),
 3.5714285714285716)

The function generates a specified number of  equispaced values in a desired range.

Numpy.linspace (  start,    stop ,   num,    dtype  )


In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Create 1D numpy array of zeros using np.zeros()


In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Create 1D numpy array of zeros using np.ones()

In [19]:
np.empty((3,3),'float')

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.20546451e-321],
       [8.34451503e-308, 9.34531021e-307, 2.56761491e-312]])

It returns the matrix with arbitrary (uninitialized) values of given shape and data types.


In [21]:
np.full((4,2),fill_value=5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(N=3,M=3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(N=3,M=3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [26]:
np.eye(N=3,M=3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

Returns the NxM matrix with value ‘1’ on the k-th diagonal and remaining entries as zero.

K = 0 represents main diagonal

K > 0 represents upper diagonal

K < 0 represents lower diagonal


# Attributes

In [29]:
x=np.array([[20,30,40,50],[45,56,78,87]])

In [30]:
x.shape

(2, 4)

In [31]:
x.size

8

In [32]:
x.ndim


2

In [34]:
x.dtype

dtype('int32')

# Reshape & Resize

In [40]:
array1=np.array([[1,2],[3,4],[5,6]])
reshaped_array=array1.reshape(2,3)
print(array1)

print("array1 shape is " ,array1.shape)

print(reshaped_array)
print("reshaped array shape is : ",reshaped_array.shape)

[[1 2]
 [3 4]
 [5 6]]
array1 shape is  (3, 2)
[[1 2 3]
 [4 5 6]]
reshaped array shape is :  (2, 3)


In [42]:
#valueerror (cannot reshape array of size 6 into shape (2,4))

In [41]:
array1=np.array([[1,2],[3,4],[5,6]])
reshaped_array=array1.reshape(2,4)
print(array1)

print("array1 shape is " ,array1.shape)

print(reshaped_array)
print("reshaped array shape is : ",reshaped_array.shape)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [49]:
array1=np.array([[1,2],[3,4],[5,6]])

array1.resize(3,3)
print(array1)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [50]:
g = np.array([1, 2, 3, 4, 5, 6])
  
# Required values 12, existing values 6
g.resize(3, 4)
  
print(g)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


# indexing & slicing

In [51]:
g = np.array([1, 2, 3, 4, 5, 6])
print("First element: ",g[0])
print("last element: ",g[-1])
print("3rd element: ",g[2])

First element:  1
last element:  6
3rd element:  3


In [52]:
x=np.array([[1,2,3],[4,5,6]])
print(x[0][1])

2


In [53]:
print(x[0,:])

[1 2 3]


In [54]:
print(x[1,:])

[4 5 6]


In [55]:
print(x[1,:2])

[4 5]


In [57]:
x1=np.array([1,2,3,4,5,6])
x1[0:4]

array([1, 2, 3, 4])

In [58]:
x1[::-1]

array([6, 5, 4, 3, 2, 1])

In [59]:
x1[0:-1:2]

array([1, 3, 5])

In [60]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n1[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [61]:
n1[2,:]

array([7, 8, 9])

In [62]:
n1[1:,:2]

array([[4, 5],
       [7, 8]])

# arithmatic operation

In [63]:
x=np.array([10,20,30,40])
y=np.array([12,3,4,6])
print("addition is : ", x+y)
print("substraction is : ",x-y)

addition is :  [22 23 34 46]
substraction is :  [-2 17 26 34]


In [64]:
print("multiplication ",x*2)

multiplication  [20 40 60 80]


# matrix & elementwise multiplication

In [65]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[2,3,4],[4,5,6],[5,6,7]])
x*y

array([[ 2,  6, 12],
       [16, 25, 36],
       [35, 48, 63]])

In [66]:
x.dot(y)

array([[ 25,  31,  37],
       [ 58,  73,  88],
       [ 91, 115, 139]])

In [69]:
score=np.array([78,89,90,100,45,20,10,67,78])
score.mean()

64.11111111111111

In [71]:
score.min()

10

In [72]:
score.max()

100

In [73]:
score.var()

912.3209876543208

In [74]:
score.std()

30.204651755223413

In [75]:
g = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
 
# before transpose
print(g, end ='\n\n')
 
# after transpose
print(g.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [77]:
g = np.array([[1, 2, 3],
                [4, 5, 6]]
                )
# before transpose
print(g, end ='\n\n')
 
# after transpose
print(g.transpose())

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [78]:
x = np.array([[10, 29],
                [4, 51],
                [71, 16]])
 
# before transpose
print(x, end ='\n\n')
 
# after transpose
print(x.transpose(1, 0))

[[10 29]
 [ 4 51]
 [71 16]]

[[10  4 71]
 [29 51 16]]


In [79]:
n= np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
   
# before transpose
print(n, end ='\n\n')
   
# after transpose
print(n.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [80]:
x=np.array([1,2,3,4])
y=np.array([2,3,4,5])
z=np.array([10,20,30,50])
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  2,  3,  4,  5, 10, 20, 30, 50])

In [82]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[2,3,4],[4,5,6],[5,6,7]])
np.concatenate([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [83]:
np.concatenate([x,y],axis=1)

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 5, 6, 7]])

# stacking

In [85]:
x=np.array([[1,2],[5,6]])
y=np.array([[4,5],[6,7]])
np.hstack([x,y])

array([[1, 2, 4, 5],
       [5, 6, 6, 7]])

In [86]:
np.vstack([x,y])

array([[1, 2],
       [5, 6],
       [4, 5],
       [6, 7]])

In [87]:
np.dstack([x,y])

array([[[1, 4],
        [2, 5]],

       [[5, 6],
        [6, 7]]])

In [88]:
print(np.ndim(np.dstack([x,y])))

3


In [90]:
arr1 =np.array(( 1, 2, 3 ))
  
arr2 = np.array(( 4, 5, 6 ))

  
# Stacking the two arrays 
arr3= np.column_stack((arr1,arr2))
print ("stacked array" ,arr3)

stacked array [[1 4]
 [2 5]
 [3 6]]


In [91]:
arr1 = np.array([[ 18,12,9], [ 81, 82, 13]] )

  
arr2 = np.array([[ 4, 5, 6], [ 14, 85, 46]] )
 
  

arr3 = np.column_stack((arr1, arr2))
print (" stacked array :\n ", arr3)

 stacked array :
  [[18 12  9  4  5  6]
 [81 82 13 14 85 46]]


# spliting

In [98]:
x=np.array([[2,3,4,6],[6,8,9,45]])

The hsplit() It is used to split an array horizontally (column-wise)


In [99]:
np.hsplit(x,2)

[array([[2, 3],
        [6, 8]]),
 array([[ 4,  6],
        [ 9, 45]])]

The vsplit() is used to split an array vertically (row-wise)


In [100]:
np.vsplit(x,2)

[array([[2, 3, 4, 6]]), array([[ 6,  8,  9, 45]])]

In [103]:
x=np.arange(30).reshape(2,5,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [106]:
np.dsplit(x,3)

[array([[[ 0],
         [ 3],
         [ 6],
         [ 9],
         [12]],
 
        [[15],
         [18],
         [21],
         [24],
         [27]]]),
 array([[[ 1],
         [ 4],
         [ 7],
         [10],
         [13]],
 
        [[16],
         [19],
         [22],
         [25],
         [28]]]),
 array([[[ 2],
         [ 5],
         [ 8],
         [11],
         [14]],
 
        [[17],
         [20],
         [23],
         [26],
         [29]]])]

In [117]:
n=np.array([1,2,3,4,5,6])
np.split(n,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [118]:
np.split(n,4)

ValueError: array split does not result in an equal division

The split() does not allow an integer (N) as a number of splits, if N does not divide the array into equal length of sub-arrays 


In [119]:
np.split(n,[1,3
           ])

[array([1]), array([2, 3]), array([4, 5, 6])]

In [120]:
x=np.arange(12)
np.array_split(x,5)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11])]

In [107]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [108]:
np.ndarray.flatten(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [110]:
x=np.array([1,2,3,4])
for i in x:
    print(i)

1
2
3
4


In [116]:
x=np.array([[1,2,3,4],[5,6,7,8]])
for i in x:
    for j in i:
        print(j)
    

1
2
3
4
5
6
7
8


# Broadcasting

The term broadcasting refers to how numpy treats arrays with different Dimension during arithmetic operations which lead to certain constraints, the smaller array 
is broadcast across the larger array so that they have compatible shapes. 

Broadcasting Rules: 

Broadcasting two arrays together follow these rules: 

If the arrays don’t have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.

The two arrays are compatible in a dimension if they have the same size in the dimension or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible with all dimensions.

After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.

In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

In [3]:
x = np.array([[51, 34, 13], [100, 200, 300]])
print(x)
 
y= 6
print(y)
 
z=x+y 
print(z)

[[ 51  34  13]
 [100 200 300]]
6
[[ 57  40  19]
 [106 206 306]]


If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar
shapes is still possible in NumPy, because of the broadcasting capability.

In [5]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([1,2,3])  
   
print('First array:') 
print(a)
  
   
print('Second array:' )
print(b)  
   
print('First Array + Second Array') 
print(a + b)

First array:
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
Second array:
[1 2 3]
First Array + Second Array
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [8]:
#The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
  
print(a)
  
print ('Indices of elements <4')
  
b = np.where(a<4)
print(b)

[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))


In [9]:
#numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

In [10]:
arr1 = [20, 29, 79, 61, 34,67,87,90,65,543,34,89]
print("arr : ", arr1)
print("50th percentile of arr : ",
       np.percentile(arr1, 50))
print("25th percentile of arr : ",
       np.percentile(arr1, 25))
print("75th percentile of arr : ",
       np.percentile(arr1, 75))

arr :  [20, 29, 79, 61, 34, 67, 87, 90, 65, 543, 34, 89]
50th percentile of arr :  66.0
25th percentile of arr :  34.0
75th percentile of arr :  87.5


In [12]:
#With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy 
#array having different elements with different sizes.

In [11]:
x = np.array([1, 2, 3, 4, 5,6,7,8,9])
list1 = [1, 3, 5]
y= np.isin(x, list1)
  
print(y)

[ True False  True False  True False False False False]
